---
services:
  relay-my-alerts:
    image: aqajooon/relay-my-alerts
    container_name: relay-my-alerts
    ports:
      - "8080:80"
    environment:
      - RMA_ENV=production
      - RMA_DEBUG=0
      - RMA_TESTING=0
      - RMA_TIMEOUT=10
      - RMA_RETRY=5
      - RMA_ZULIP_ENABLED=**********
      - RMA_ZULIP_API_URL=***********
      - RMA_ZULIP_BOT_EMAIL=************
      - RMA_ZULIP_API_KEY=***********
      - RMA_ZULIP_CHANNEL=**********
      - RMA_ZULIP_TOPIC=************
      - RMA_MATTERMOST_ENABLED=***********
      - RMA_MATTERMOST_WEBHOOK_URL=*********
      - RMA_ZOHO_ENABLED=**********
      - RMA_ZOHO_WEBHOOK_URL=**********
      - RMA_BIND_ADDRESS=0.0.0.0:80
      - RMA_NUM_WOEKERS=4
